name: widgets_from_html
description: "A package that exposes widgets_from_html_core and other extensions."
version: 0.0.2-dev.1
homepage: https://aryak.dev/packages/widgets_from_html
issue_tracker: https://github.com/devaryakjha/html_parser/issues
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  widgets_from_html_core:
    path: ./packages/widgets_from_html_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
