name: widgets_from_html
description: "A package to render HTML content as Flutter widgets. Supports all basic HTML tags."
version: 0.0.2-dev.1
homepage: https://github.com/devaryakjha/html_parser
issue_tracker: https://github.com/devaryakjha/html_parser/issues

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  gap: ^3.0.1
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
