name: widgets_from_html_core
description: "A convenience package for rendering HTML content as Flutter widgets."
version: 0.0.1-dev.1
homepage: https://aryak.dev/packages/widgets_from_html

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

# The following section is specific to Flutter packages.
flutter: